# Generated by Django 4.0.1 on 2022-01-16 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_eavoteuser_public_key_alter_eavoteuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eavoteuser',
            name='ea_election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.eaelection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eaelection',
            name='voter_list',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='eavoteuser',
            name='userid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9aa1fefe-5917-46c9-b59c-a076e21fbd23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
