# Generated by Django 4.0.1 on 2022-01-16 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_eavoteuser_ea_election_alter_eaelection_voter_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eavoteuser',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eavoteuser',
            name='userid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e15dcf9d-379c-42a1-a8b5-3f6d30eeb1ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
