# Generated by Django 4.0.1 on 2022-01-17 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_eavoteuser_name_alter_eavoteuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eavoteuser',
            name='userid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
