# Generated by Django 4.0.1 on 2022-01-17 05:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eovote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EoCredentialUser',
            fields=[
                ('userid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('public_key', models.CharField(max_length=255)),
                ('eo_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eovote.eoelection')),
            ],
        ),
    ]
