# Generated by Django 4.0.1 on 2022-01-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eovote', '0002_eocredentialuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eocredentialuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eocredentialuser',
            name='public_key',
        ),
    ]
